doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '16'
                use_savepoints: true
                profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Users:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Database'
                prefix: 'App\User\Domain\Entity'
                alias: User
                mapping: true
            UserValueObjects:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/ValueObject'
                prefix: 'App\User\Domain\ValueObject'
                alias: UserValueObjects
                mapping: true
            RefreshToken:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Database'
                prefix: 'App\User\Domain\Entity'
                alias: RefreshToken
                mapping: true
            Page:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/UserPage/Infrastructure/Database'
                prefix: 'App\UserPage\Domain\Entity'
                alias: Page
                mapping: true
            Link:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/UserPage/Infrastructure/Database'
                prefix: 'App\UserPage\Domain\Entity'
                alias: Link
                mapping: true
        controller_resolver:
            auto_mapping: false
#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
