when@dev:
    framework:
        messenger:
            default_bus: command.bus
            buses:
                command.bus:
                    middleware:
                        - doctrine_transaction
                query.bus:
            transports:
                async: '%env(MESSENGER_TRANSPORT_DSN)%'
            routing:
                App\Statistics\Application\UseCase\Command\CreatePageVisit\CreatePageVisitCommand: async
                App\Statistics\Application\UseCase\Command\CreateLinkClick\CreateLinkClickCommand: async

when@test:
    framework:
        messenger:
            default_bus: command.bus
            buses:
                command.bus:
                    middleware:
                        - doctrine_transaction
                query.bus:
