services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Resources\Fixture\Common\:
        resource: "%kernel.project_dir%/tests/Resources/Fixture/Common/*"
        tags:
            - { "name": "doctrine.fixture.orm" }

    App\Tests\Resources\Fixture\Custom\:
        resource: "%kernel.project_dir%/tests/Resources/Fixture/Custom/*"
        public: true

    App\Shared\Infrastructure\Bus\CommandBus:
        public: true

    App\Shared\Infrastructure\Bus\QueryBus:
        public: true